# Generated by Django 2.2 on 2020-08-04 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskCreated',
            new_name='Task',
        ),
    ]
