# Generated by Django 2.2 on 2020-08-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0002_auto_20200804_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='open',
            field=models.BooleanField(default=False),
        ),
    ]
