# Generated by Django 2.2 on 2020-08-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0004_auto_20200805_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='schedule',
            field=models.DateField(),
        ),
    ]
